version: '2'
services:
  web:
    image: cvermeul/php-mysql:5.6-apache
    container_name: web
    ports: 
      - "80:80"
    volumes:
      - .:/var/www/html
    environment:
      - APP_DB_HOST=${DB_HOST}
      - APP_DB_USER=${DB_USER}
      - APP_DB_PASSWORD=${DB_PASSWORD}
    external_links:
      - mysql
    network_mode: "bridge"
